services:
  db:
    image: postgres:17.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=meari
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=cloud_file_storage
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
  minio:
    image: docker.io/bitnami/minio:2025
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - app-network
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=meariuser
      - MINIO_ROOT_PASSWORD=12345678
      - MINIO_DEFAULT_BUCKETS=user-files
  redis:
    image: redis:7.4.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=mearipass
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
  app:
    image: cloud-file-storage-backend:0.0.1
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cloud_file_storage
      SPRING_DATASOURCE_USERNAME: meari
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - db
    networks:
      - app-network
  front:
    image: cloud-front-test:latest
    ports:
      - '80:80'
    networks:
      - app-network
volumes:
  pg_data:
  minio_data:
    driver: local
networks:
  app-network:
    driver: bridge