services:
  db:
    image: postgres:17.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=meari
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=cloud_file_storage
    volumes:
      - pg_data:/var/lib/postgresql/data
  minio:
    image: docker.io/bitnami/minio:2025
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - app-network
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=meariuser
      - MINIO_ROOT_PASSWORD=12345678
      - MINIO_DEFAULT_BUCKETS=user-files
volumes:
  pg_data:
  minio_data:
    driver: local
networks:
  app-network:
    driver: bridge