services:
  db:
    image: postgres:17.2
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
  minio:
    image: docker.io/bitnami/minio:2025
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - app-network
    volumes:
      - 'minio_data:/data'
    env_file:
      - .env
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: always
  app:
    image: cloud-file-storage-backend:latest
    ports:
      - '8080:8080'
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - db
      - minio
      - redis
  front:
    image: fakechitor/cloud-file-storage-frontend:1.0.0
    ports:
      - '80:80'
    networks:
      - app-network
volumes:
  pg_data:
  minio_data:
    driver: local
  redis_data:
networks:
  app-network:
    driver: bridge