services:
  db:
    image: postgres:17.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=meari
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=cloud_file_storage
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: