spring:
  application:
    name: cloud-file-storage
  datasource:
    url: jdbc:postgresql://db:5432/cloud_file_storage
    driver-class-name: org.postgresql.Driver
    username: meari
    password: 123456
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  data:
    redis:
      host: localhost
      port: 6379
minio:
  endpoint: http://minio:9000
  access-key: meariuser
  secret-key: 12345678
